[package]
name = "command_wrapper"
version = "0.1.0"
authors = ["Roxana Nicolescu <nicolescu.roxana1996@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
